### ISSUE TITLE
Preferential Sampling

### ISSUE THREAD

**Issue by MartaMarchiori** [arb7/adv-deb-multi#1]
Hi there, 

thanks for your work, I am studying your paper _Differential Tweetment: Mitigating Racial Dialect Bias in Harmful Tweet Detection_ and I find it very inspiring!

I was wondering, is there any "open-source" version of the code you used for performing Preferential Sampling? 
I am also reading the works of Kamiran and Calders, but I haven't found an implementation of their approach or your modified strategy. 

Thanks a lot, 

Marta

**Comment by arb7** [comment]
Hi Marta!

I still have a copy of the preferential sampling code, but it's quite messy and much of the implementation is very specific to that use case. I'm happy to share it with you (it might still be useful to see how it worked in our research). Just email me at arb229 [at] cantab [dot] ac [dot] uk and I'll send it over.

Best,
Ari
