### ISSUE TITLE
Reloading a saved model

### ISSUE THREAD

**Issue by minasmz** [arb7/adv-deb-multi#2]
Hi there,

Thank you for sharing your code. I found it very useful but I have difficulty reloading the saved TensorFlow models for prediction. Since I am trying to call the prediction method multiple times on the same saved model, It would be super helpful if I be able to reload a saved model. I appreciate your help and suggestions.

Thank you in advance!

**Comment by arb7** [comment]
Hello! Glad you've been using and enjoying the code. This functionality has been implemented but may not be so clear (and certainly isn't well-documented), so I'll try to clarify here.

The AdversarialDebiasingMulti class has an attribute saved_model which abstracts away TensorFlow's saving functionality (this was one of my additions to IBM's code, as I was working with some very large datasets and wanted to make predictions on external datasets). Just add a model name when you instantiate, e.g. model = AdversarialDebiasingMulti(..., saved_model=my_model_name). Then, when you call fit, the saved model with that name is retrieved (lines 210-216). If no model with that name exists (including the first call with a given model name or after deleting a saved model) it'll print the retrieval error and continue to fit to the data (lines 217-222), then save the model with that name (lines 257-262). Then, call predict as usual.

Hope this helps, let me know if you have further questions or any of this is unclear.
